import * as path from 'path';
import { WebsiteProject } from './types';

function esc(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/**
 * websiteRelFromFake: e.g. "..\\..\\..\\Legacy.WebSite"
 * hintByDll: dllName -> HintPath (relative to fake project dir)
 */
export function generateFakeCsproj(
  website: WebsiteProject,
  websiteRelFromFake: string,
  hintByDll: Map<string, string>,
  generatedDirName?: string
): string {
  const prefix = websiteRelFromFake.replace(/\//g, '\\').replace(/\\+$/, '');

  const compileInclude = esc(path.join(prefix, '**', '*.cs')).replace(/\//g, '\\');
  const compileExclude = [
    path.join(prefix, 'obj', '**'),
    path.join(prefix, 'bin', '**'),
    path.join(prefix, 'Bin', '**'),
    path.join(prefix, 'App_Data', '**'),
    path.join(prefix, 'Packages', '**'),
    path.join(prefix, 'node_modules', '**'),
    path.join(prefix, '**', 'Temporary ASP.NET Files', '**'),
    path.join(prefix, 'Properties', 'AssemblyInfo.cs'),
  ].map(s => s.replace(/\//g, '\\')).join(';');

  const contentPatterns = ['aspx', 'ascx', 'master', 'ashx', 'asmx', 'config', 'asax'].map(ext => {
    const inc = esc(path.join(prefix, '**', `*.${ext}`)).replace(/\//g, '\\');
    return `    <Content Include="${inc}" />`;
  }).join('\n');

  const projectReferences = website.projectReferences
    .filter(ref => ref.projectPath)
    .map(ref => {
      const include = esc(ref.projectPath || '');
      const projectGuid = esc(ref.guid.toUpperCase());
      const projectName = esc(path.basename(ref.projectPath || '', path.extname(ref.projectPath || '')));

      return `    <ProjectReference Include="${include}">
      <Project>{${projectGuid}}</Project>
      <Name>${projectName}</Name>
    </ProjectReference>`;
    }).join('\n');

  const projectDllNames = new Set(
    website.projectReferences
      .filter(ref => ref.projectPath)
      .map(ref => ref.dllName.toLowerCase())
  );

  const references = Array.from(hintByDll.entries())
    .filter(([dllName]) => !projectDllNames.has(dllName.toLowerCase()))
    .map(([dllName, hintPath]) => {
      const includeName = esc(dllName.replace(/\.dll$/i, ''));
      const hint = esc(hintPath || path.join(prefix, 'Bin', dllName)).replace(/\//g, '\\');

      return `    <Reference Include="${includeName}">
      <HintPath>${hint}</HintPath>
      <Private>False</Private>
    </Reference>`;
    }).join('\n');

  const generatedCompileInclude = generatedDirName
    ? esc(path.join(generatedDirName, '**', '*.cs')).replace(/\//g, '\\')
    : undefined;

  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by sln2csproj -->
<!-- IntelliSense only; do not use for real builds -->
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{${website.guid}}</ProjectGuid>
    <OutputType>Library</OutputType>
    <RootNamespace>${esc(website.name.replace(/\./g, '_'))}</RootNamespace>
    <AssemblyName>${esc(website.name)}</AssemblyName>
    <TargetFrameworkVersion>${esc(website.targetFramework)}</TargetFrameworkVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Data" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Web" />
    <Reference Include="System.Web.Extensions" />
    <Reference Include="System.Web.Services" />
    <Reference Include="System.Xml" />
    <Reference Include="System.Configuration" />
    <Reference Include="System.Xml.Linq" />

${references}
  </ItemGroup>

  <ItemGroup>
${projectReferences}
  </ItemGroup>

  <ItemGroup>
    <Compile Include="${compileInclude}" Exclude="${esc(compileExclude)}" />
${generatedCompileInclude ? `    <Compile Include="${generatedCompileInclude}" />` : ''}
  </ItemGroup>

  <ItemGroup>
${contentPatterns}
  </ItemGroup>

  <Import Project="$(MSBuildToolsPath)\\Microsoft.CSharp.targets" />

  <Target Name="Build">
    <Message Text="[INFO] fake csproj for IntelliSense only" Importance="high" />
  </Target>
</Project>`;
}
