import * as fs from 'fs';
import * as path from 'path';
import { mkdirp, readText, writeText } from './io';

const MARKUP_FILE_RE = /\.(aspx|ascx|master)$/i;

export interface ShimGenerationResult {
  generatedCount: number;
  generatedDirName?: string;
}

interface ServerControlDeclaration {
  id: string;
  typeName: string;
}

interface RegisterDirective {
  tagPrefix: string;
  tagName?: string;
  namespaceName?: string;
  assemblyName?: string;
  src?: string;
}

export function generateWebFormsShimFiles(fakeDirAbs: string, websiteAbs: string): ShimGenerationResult {
  const markupFiles = collectMarkupFiles(websiteAbs);
  const generatedDirAbs = path.join(fakeDirAbs, 'generated');
  let generatedCount = 0;

  for (const markupPath of markupFiles) {
    const shim = buildShim(markupPath);
    if (!shim) {
      continue;
    }

    mkdirp(generatedDirAbs);
    const relativeMarkup = path.relative(websiteAbs, markupPath).replace(/[\\/]/g, '_');
    const outputName = `${relativeMarkup}.intellisense.g.cs`;
    writeText(path.join(generatedDirAbs, outputName), shim);
    generatedCount++;
  }

  return generatedCount > 0
    ? { generatedCount, generatedDirName: 'generated' }
    : { generatedCount: 0 };
}

function buildShim(markupPath: string): string | undefined {
  const markup = readText(markupPath);
  const inherits = parseAttribute(markup, 'Inherits');
  if (!inherits) {
    return undefined;
  }

  const registerDirectives = parseRegisterDirectives(markup);
  const declarations = parseServerControlDeclarations(markup, markupPath, registerDirectives);
  if (declarations.length === 0) {
    return undefined;
  }

  const designerPath = `${markupPath}.designer.cs`;
  const existingFields = readDesignerFieldNames(designerPath);
  const missingFields = declarations.filter(item => !existingFields.has(item.id));
  if (missingFields.length === 0) {
    return undefined;
  }

  const { namespaceName, className } = splitTypeName(inherits);
  const fieldLines = missingFields
    .map(item => `        protected global::${item.typeName} ${item.id};`)
    .join('\n');

  if (namespaceName) {
    return [
      '// Generated by sln2csproj for IntelliSense only.',
      `namespace ${namespaceName} {`,
      `    public partial class ${className} {`,
      fieldLines,
      '    }',
      '}',
      '',
    ].join('\n');
  }

  return [
    '// Generated by sln2csproj for IntelliSense only.',
    `public partial class ${className} {`,
    fieldLines,
    '}',
    '',
  ].join('\n');
}

function parseAttribute(text: string, attributeName: string): string | undefined {
  const match = text.match(new RegExp(`${attributeName}\\s*=\\s*(['"])(.*?)\\1`, 'i'));
  return match?.[2]?.trim();
}

function parseTagAttributes(text: string): Record<string, string> {
  const attributes: Record<string, string> = {};
  const regex = /([A-Za-z_:][\w:.-]*)\s*=\s*(?:(['"])(.*?)\2|([^\s"'=<>`]+))/gs;

  for (const match of text.matchAll(regex)) {
    const name = match[1]?.toLowerCase();
    const value = (match[3] || match[4] || '').trim();
    if (name && value) {
      attributes[name] = value;
    }
  }

  return attributes;
}

function parseRegisterDirectives(markup: string): RegisterDirective[] {
  const directives: RegisterDirective[] = [];
  const directiveRegex = /<%@\s*Register\b([\s\S]*?)%>/gi;

  for (const match of markup.matchAll(directiveRegex)) {
    const attributes = parseTagAttributes(match[1] || '');
    const tagPrefix = attributes.tagprefix;
    if (!tagPrefix) {
      continue;
    }

    directives.push({
      tagPrefix,
      tagName: attributes.tagname,
      namespaceName: attributes.namespace,
      assemblyName: attributes.assembly,
      src: attributes.src,
    });
  }

  return directives;
}

function parseServerControlDeclarations(
  markup: string,
  markupPath: string,
  registerDirectives: RegisterDirective[]
): ServerControlDeclaration[] {
  const tagRegex = /<([A-Za-z][\w:.:-]*)(\s[^<>]*?)?(\/?)>/gs;
  const controls = new Map<string, ServerControlDeclaration>();

  for (const match of markup.matchAll(tagRegex)) {
    const tagName = match[1];
    if (!tagName || tagName.startsWith('%') || tagName.startsWith('/')) {
      continue;
    }

    const attributes = parseTagAttributes(match[2] || '');
    if ((attributes.runat || '').toLowerCase() !== 'server') {
      continue;
    }

    const id = attributes.id;
    if (!id || !isValidIdentifier(id)) {
      continue;
    }

    controls.set(id, {
      id,
      typeName: inferControlType(tagName, attributes, markupPath, registerDirectives),
    });
  }

  return Array.from(controls.values());
}

function isValidIdentifier(value: string): boolean {
  return /^[A-Za-z_][A-Za-z0-9_]*$/.test(value);
}

function inferControlType(
  tagName: string,
  attributes: Record<string, string>,
  markupPath: string,
  registerDirectives: RegisterDirective[]
): string {
  const normalized = tagName.toLowerCase();

  if (normalized.startsWith('asp:')) {
    return inferAspControlType(tagName.slice(4));
  }

  if (normalized.includes(':')) {
    return inferRegisteredControlType(tagName, markupPath, registerDirectives) || 'System.Web.UI.UserControl';
  }

  switch (normalized) {
    case 'input':
      return inferHtmlInputType(attributes.type);
    case 'textarea':
      return 'System.Web.UI.HtmlControls.HtmlTextArea';
    case 'select':
      return 'System.Web.UI.HtmlControls.HtmlSelect';
    case 'form':
      return 'System.Web.UI.HtmlControls.HtmlForm';
    case 'a':
      return 'System.Web.UI.HtmlControls.HtmlAnchor';
    case 'img':
      return 'System.Web.UI.HtmlControls.HtmlImage';
    case 'table':
      return 'System.Web.UI.HtmlControls.HtmlTable';
    case 'tr':
      return 'System.Web.UI.HtmlControls.HtmlTableRow';
    case 'td':
    case 'th':
      return 'System.Web.UI.HtmlControls.HtmlTableCell';
    case 'button':
      return 'System.Web.UI.HtmlControls.HtmlButton';
    default:
      return 'System.Web.UI.HtmlControls.HtmlGenericControl';
  }
}

function inferAspControlType(shortName: string): string {
  const normalized = shortName.trim();
  return normalized
    ? `System.Web.UI.WebControls.${normalized}`
    : 'System.Web.UI.Control';
}

function inferRegisteredControlType(
  tagName: string,
  markupPath: string,
  registerDirectives: RegisterDirective[]
): string | undefined {
  const [prefix, shortName] = tagName.split(':', 2);
  if (!prefix || !shortName) {
    return undefined;
  }

  const prefixLower = prefix.toLowerCase();
  const shortNameLower = shortName.toLowerCase();

  for (const directive of registerDirectives) {
    if (directive.tagPrefix.toLowerCase() !== prefixLower) {
      continue;
    }

    if (directive.src) {
      if (directive.tagName && directive.tagName.toLowerCase() !== shortNameLower) {
        continue;
      }

      const resolved = resolveRegisteredSrcType(markupPath, directive.src);
      if (resolved) {
        return resolved;
      }
    }

    if (directive.namespaceName) {
      if (directive.tagName && directive.tagName.toLowerCase() !== shortNameLower) {
        continue;
      }

      return `${directive.namespaceName}.${shortName}`;
    }
  }

  return undefined;
}

function resolveRegisteredSrcType(markupPath: string, src: string): string | undefined {
  const relative = src.replace(/^~\//, '').replace(/\//g, path.sep);
  const rooted = src.startsWith('~/');
  const markupDir = path.dirname(markupPath);
  const websiteRoot = findWebsiteRoot(markupDir);
  const candidate = rooted
    ? path.join(websiteRoot, relative)
    : path.resolve(markupDir, src);

  if (!fs.existsSync(candidate)) {
    return undefined;
  }

  const text = readText(candidate);
  return parseAttribute(text, 'Inherits');
}

function findWebsiteRoot(startDir: string): string {
  let current = startDir;

  while (true) {
    const parent = path.dirname(current);
    if (parent === current) {
      return startDir;
    }

    if (fs.existsSync(path.join(current, 'web.config'))) {
      return current;
    }

    current = parent;
  }
}

function inferHtmlInputType(typeValue?: string): string {
  switch ((typeValue || '').toLowerCase()) {
    case 'hidden':
      return 'System.Web.UI.HtmlControls.HtmlInputHidden';
    case 'password':
      return 'System.Web.UI.HtmlControls.HtmlInputPassword';
    case 'checkbox':
      return 'System.Web.UI.HtmlControls.HtmlInputCheckBox';
    case 'radio':
      return 'System.Web.UI.HtmlControls.HtmlInputRadioButton';
    case 'file':
      return 'System.Web.UI.HtmlControls.HtmlInputFile';
    case 'submit':
    case 'button':
    case 'reset':
      return 'System.Web.UI.HtmlControls.HtmlInputButton';
    case 'image':
      return 'System.Web.UI.HtmlControls.HtmlInputImage';
    default:
      return 'System.Web.UI.HtmlControls.HtmlInputText';
  }
}

function readDesignerFieldNames(designerPath: string): Set<string> {
  if (!fs.existsSync(designerPath)) {
    return new Set<string>();
  }

  const text = readText(designerPath);
  const matches = text.matchAll(/\b(?:protected|public|private|internal)\s+(?:global::)?[\w.<>,]+\s+(\w+)\s*;/g);
  const fields = new Set<string>();
  for (const match of matches) {
    if (match[1]) {
      fields.add(match[1]);
    }
  }
  return fields;
}

function splitTypeName(typeName: string): { namespaceName?: string; className: string } {
  const trimmed = typeName.trim();
  const lastDot = trimmed.lastIndexOf('.');
  if (lastDot === -1) {
    return { className: trimmed };
  }

  return {
    namespaceName: trimmed.slice(0, lastDot),
    className: trimmed.slice(lastDot + 1),
  };
}

function collectMarkupFiles(rootDir: string): string[] {
  const files: string[] = [];
  walk(rootDir, files);
  return files;
}

function walk(currentDir: string, files: string[]): void {
  for (const entry of fs.readdirSync(currentDir, { withFileTypes: true })) {
    const fullPath = path.join(currentDir, entry.name);
    if (entry.isDirectory()) {
      if (shouldSkipDirectory(entry.name)) {
        continue;
      }
      walk(fullPath, files);
      continue;
    }

    if (MARKUP_FILE_RE.test(entry.name)) {
      files.push(fullPath);
    }
  }
}

function shouldSkipDirectory(name: string): boolean {
  return /^(bin|obj|node_modules|app_data|packages|_intellisense)$/i.test(name);
}
